apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-app-staging-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/ecommerce-app.git
    targetRevision: HEAD
    path: helm/ecommerce-app
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.environment
          value: staging
        - name: global.imageRegistry
          value: your-registry.azurecr.io
        - name: frontend.image.tag
          value: latest
        - name: backend.image.tag
          value: latest
        - name: payment.image.tag
          value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas 