{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-app-secrets
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-mongodb-secrets
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-root-password: {{ .Values.secrets.mongodbPassword | b64enc }}
{{- end }} 